;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Encounter",DevComment="Tags for different encounter characters")
+GameplayTagList=(Tag="Encounter.Accessories",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Beard",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Glasses",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.MaidsCap",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Patch",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Tie",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Hats",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Hats.MerryMaids",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Underwear",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender.Female",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender.Male",DevComment="")
+GameplayTagList=(Tag="Gameplay",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.JohnDoeAllowed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishop",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishopDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishopEntered",DevComment="")
+GameplayTagList=(Tag="PlayerItem",DevComment="")
+GameplayTagList=(Tag="PlayerItem.GreenManBobble",DevComment="")
+GameplayTagList=(Tag="PlayerItem.MusicBox",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Phone",DevComment="")
+GameplayTagList=(Tag="PlayerItem.SingingFish",DevComment="")
+GameplayTagList=(Tag="PlayerItem.SteelEggSwingingBalls",DevComment="")

