;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Gameplay.Character.JohnDoeAllowed",NewTagName="Gameplay.Character.BenJones")
+GameplayTagRedirects=(OldTagName="PlayerItem.GreenManBobble",NewTagName="PlayerItem.Green_Man_Bobble")
+GameplayTagRedirects=(OldTagName="PlayerItem.MusicBox",NewTagName="PlayerItem.Music_Box")
+GameplayTagRedirects=(OldTagName="PlayerItem.SingingFish",NewTagName="PlayerItem.Singing_Fish")
+GameplayTagRedirects=(OldTagName="PlayerItem.SteelEggSwingingBalls",NewTagName="PlayerItem.Egg_Pendulum")
+GameplayTagRedirects=(OldTagName="PlayerItem.Green_Man_Bobble",NewTagName="PlayerItem.Bobble")
+GameplayTagList=(Tag="Encounter",DevComment="Tags for different encounter characters")
+GameplayTagList=(Tag="Encounter.Accessories",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Beard",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Glasses",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.MaidsCap",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Patch",DevComment="")
+GameplayTagList=(Tag="Encounter.Accessories.Tie",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Hats",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Hats.MerryMaids",DevComment="")
+GameplayTagList=(Tag="Encounter.Clothes.Underwear",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender.Female",DevComment="")
+GameplayTagList=(Tag="Encounter.Gender.Male",DevComment="")
+GameplayTagList=(Tag="Gameplay",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.BenJones",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.BenJonesAllowed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.BenJonesDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.Joan",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.JoanAllowed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.JoanDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrBishop",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrBishopAllowed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrBishopDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishop",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishopDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.MrsBishopEntered",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.PCMac",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.PCMacAllowed",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.PCMacDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.Stan",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.StanDenied",DevComment="")
+GameplayTagList=(Tag="Gameplay.Character.StanEntered",DevComment="")
+GameplayTagList=(Tag="PlayerItem",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Bobble",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Brooch",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Egg_Pendulum",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Music_Box",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Phone",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Singing_Fish",DevComment="")
+GameplayTagList=(Tag="PlayerItem.Trophy",DevComment="")

